# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
- jekyll-compass
- jekyll-press

# Site settings
title: Nikolay Turnaviotov
email: fox@mulder.kiev.ua
#description: > # this means to ignore newlines until "baseurl:"
#  Это мой будущий сайт на Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mulder.kiev.ua" # the base hostname & protocol for your site
twitter_username: fox_mulder_cp
github_username:  foxmuldercp

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path:   ""
    values:
      lang:   ru
      layout: page
  -
    scope:
      path:   ru
    values:
      lang:   ru
      layout: page
  -
    scope:
      path:   en
    values:
      lang:   en
      layout: page

collections:
  ru:
    output:       true
    lang:         ru
    title:        Ru
    short:        Главная
  posts:
    title:        Blog / Дневник
    layout:       post
    output:       true
    short:        Записи дневника
  stories:
    title:        Мои короткие истории
    short:        Мои короткие истории
    output:       true
  tech:
    title:        Техническое
    short:        Техническое
    output:       true
  en:
    output:       true
    lang:         en
    title:        En
    short:        Index

google_analytics: "UA-8017247-3"

social:
  github: foxmuldercp
  twitter: fox_mulder_cp
  facebook: turnaviotovnn
  email: turnaviotovnn@gmail.com

jekyll-press:
  exclude: 'feed.xml'